{"historyId": "4e10b690c9fce82df6e8e5b0914e3faf", "links": [{"name": "搜索功能", "url": "搜索功能", "type": "test_case"}], "start": 1666322920533, "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "searchTest"}, {"name": "host", "value": "DESKTOP-2N4CHJQ"}, {"name": "thread", "value": "25812-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.searchTest"}], "testCaseId": "97ed200b7629516bbb23d3c2d518fd1f", "uuid": "da5c23a7-dca4-4900-9a27-1dbe98218220", "parameters": [{"name": "test_data", "value": "'allure'"}], "name": "test_SearchFun[allure]", "stop": 1666322920533, "fullName": "cases.searchTest#test_SearchFun", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'help.yaml'", "trace": "test_data = 'allure'\n\n    @allure.testcase(\"搜索功能\")\n    @pytest.mark.parametrize('test_data',['selenium','allure'])\n    def test_SearchFun(test_data):\n    \n>       with open(\"help.yaml\", encoding='utf-8') as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'help.yaml'\n\nsearchTest.py:14: FileNotFoundError"}, "status": "broken"}